set(_CATKIN_CURRENT_PACKAGE "MoveIT")
set(MoveIT_VERSION "0.3.0")
set(MoveIT_MAINTAINER "Gayathri_MoveIT <gayathri.gude@colorado.edu>")
set(MoveIT_PACKAGE_FORMAT "1")
set(MoveIT_BUILD_DEPENDS "fetch_description")
set(MoveIT_BUILD_EXPORT_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "tf2_ros" "xacro" "fetch_description")
set(MoveIT_BUILDTOOL_DEPENDS "catkin")
set(MoveIT_BUILDTOOL_EXPORT_DEPENDS )
set(MoveIT_EXEC_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "tf2_ros" "xacro" "fetch_description")
set(MoveIT_RUN_DEPENDS "moveit_ros_move_group" "moveit_fake_controller_manager" "moveit_kinematics" "moveit_planners_ompl" "moveit_ros_visualization" "moveit_setup_assistant" "joint_state_publisher" "robot_state_publisher" "tf2_ros" "xacro" "fetch_description")
set(MoveIT_TEST_DEPENDS )
set(MoveIT_DOC_DEPENDS )
set(MoveIT_URL_WEBSITE "http://moveit.ros.org/")
set(MoveIT_URL_BUGTRACKER "https://github.com/ros-planning/moveit/issues")
set(MoveIT_URL_REPOSITORY "https://github.com/ros-planning/moveit")
set(MoveIT_DEPRECATED "")