controller_list:
  - name: fake_fetch_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - upperarm_roll_joint
      - elbow_flex_joint
      - forearm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
      - l_gripper_finger_joint
      - r_gripper_finger_joint